
name: CI

on:
  push:
    branches: [ "main" ]

# env:
#   PUBLIC_SITE: https://takakiaraki09.github.io
#   PUBLIC_SITE_BASE: TakakiAraki09

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: キャッシュ node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: install dpendencies
        run: pnpm i --frozen-lockfile

      - name: check build
        run: pnpm run build

      - uses: actions/upload-artifact@v3
        with:
          name: apexTaimanCounter
          path: _release

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
